### ISSUE TITLE
Invalid Header Value 

### ISSUE THREAD

**Issue by audrey-dogman** [alxgmpr/PyNode#1]
I am using Ubuntu 16.04. When launching, it gets to the end of the config stage and says that the Header Value is invalid. I suspect that it's adding a new line at the end of the key, but I have checked a million times and there is no new line at the end of the apikey.txt file.

Here's the full traceback:
> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
>     self.run()
>   File "main.py", line 426, in run
>     self.generate_linode()
>   File "main.py", line 143, in generate_linode
>     region = client.get_regions()[3]
>   File "/home/audrey/.local/lib/python2.7/site-packages/linode/linode_client.py", line 518, in get_regions
>     return self._get_and_filter(Region, *filters)
>   File "/home/audrey/.local/lib/python2.7/site-packages/linode/linode_client.py", line 658, in _get_and_filter
>     return self._get_objects(obj_type.api_list(), obj_type, filters=parsed_filters)
>   File "/home/audrey/.local/lib/python2.7/site-packages/linode/linode_client.py", line 489, in _get_objects
>     response_json = self.get(endpoint, model=model, filters=filters)
>   File "/home/audrey/.local/lib/python2.7/site-packages/linode/linode_client.py", line 505, in get
>     return self._api_call(*args, method=requests.get, **kwargs)
>   File "/home/audrey/.local/lib/python2.7/site-packages/linode/linode_client.py", line 462, in _api_call
>     response = method(url, headers=headers, data=body)
>   File "/home/audrey/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
>     return request('get', url, params=params, **kwargs)
>   File "/home/audrey/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/home/audrey/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/home/audrey/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
>     r = adapter.send(request, **kwargs)
>   File "/home/audrey/.local/lib/python2.7/site-packages/requests/adapters.py", line 440, in send
>     timeout=timeout
>   File "/home/audrey/.local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 601, in urlopen
>     chunked=chunked)
>   File "/home/audrey/.local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 357, in _make_request
>     conn.request(method, url, **httplib_request_kw)
>   File "/usr/lib/python2.7/httplib.py", line 1057, in request
>     self._send_request(method, url, body, headers)
>   File "/usr/lib/python2.7/httplib.py", line 1096, in _send_request
>     self.putheader(hdr, value)
>   File "/usr/lib/python2.7/httplib.py", line 1035, in putheader
>     raise ValueError('Invalid header value %r' % (one_value,))
> ValueError: Invalid header value 'Bearer 296d3[snip, API key]5bcfe7\n'
>

**Comment by alxgmpr** [comment]
On the last line of that traceback it says you have a `/n` character at the end of the api key.

Open apikey.txt and check to make sure the 64 character api key is all that's in the file (no new lines or spaces).

I just pushed a commit to check for `/n` characters in the apikey.txt file and if so remove them. 

Please open another issue if the problem persists.
